# Site title and subtitle. This is used in _includes/header.html
title: 'Bono Documentation'
subtitle: 'Bono Oficial Documentation Site'
product: 'Bono PHP Framework'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'http://github.com/xinix-technology/bono-docs'

# Default categories (in order) to appear in the navigation
sections: [
    ['doc', 'Documentation'],
    ['ref', 'Reference'],
    ['dev', 'Developers']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: '/:categories/:title'

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md', 'Rakefile']

# Use the kramdawn Markdown renderer
markdown: KramdownPygments

# Kramdown configuration
kramdown:
    input: GFM
